org: drochag1
app: worldtime
service: api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    GOOGLE_MAPS_API_KEY: ${param:GOOGLE_MAPS_API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin
  getPlaces:
    handler: handler.getPlaces
    events:
      - http:
          path: /get-places
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin
  getExtendedSuggestion:
    handler: handler.getExtendedSuggestion
    timeout: 10
    events:
      - http:
          path: /get-extended-suggestion
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Allow-Origin
